version: 0.2

phases:
  build:
    commands:
      - echo "CodeBuild runtime identity:"
      - aws sts get-caller-identity
      - echo "Reading flag:"
      - aws secretsmanager get-secret-value --secret-id flag_codebuild_lab_5 --region us-east-1 --query SecretString --output text
